version: '3.7'

services:
  spring-petclinic:
    image: maulanaibrahim/spring-petclinic:latest
    container_name: spring-petclinic
    ports:
      - 127.0.0.1:8080:8080
    restart: always
    environment:
      - POSTGRES_URL=${POSTGRES_URL}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    networks:
      - main-network
networks:
  main-network:
    external: true