{
 "title": "SERVER-MONITORING",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "server_name",
    "label": "Server Name",
    "query": {
     "query": "label_values(node_cpu_seconds_total, job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(time() - node_boot_time_seconds{job=\"$server_name\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{job=\"$server_name\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "CPU Usage"
    },
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"idle\"}[30m])) * 100)",
     "legendFormat": "CPU Busy"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=\"$server_name\"} / (node_memory_MemTotal_bytes{job=\"$server_name\"})))* 100",
     "legendFormat": "Used RAM Memory"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$server_name\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=\"$server_name\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Used Max Mount /"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic(EXT4/XFS)",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"$server_name\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=\"$server_name\",fstype=~\"ext4|xfs\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{job=\"$server_name\",fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{job=\"$server_name\",fstype=~\"ext4|xfs\"})"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{job=\"$server_name\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU IOwait",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"iowait\"}[30m])) * 100"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_load1{job=\"$server_name\"}",
     "legendFormat": "System-Load_1m"
    },
    {
     "expr": "node_load5{job=\"$server_name\"}",
     "legendFormat": "System-Load_5m"
    },
    {
     "expr": "node_load15{job=\"$server_name\"}",
     "legendFormat": "System-Load_15m"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"system\"}[5m])) by (instance)",
     "legendFormat": "CPU-Basic_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"user\"}[5m])) by (instance)",
     "legendFormat": "CPU-Basic_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{job=\"$server_name\",mode=\"iowait\"}[5m])) by (instance)",
     "legendFormat": "CPU-Basic_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{job=\"database-production\",mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "CPU-Basic_Total"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$server_name\"}",
     "legendFormat": "Memory-Basic_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=\"$server_name\"} - node_memory_MemAvailable_bytes{job=\"$server_name\"}",
     "legendFormat": "Memory-Basic_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{job=\"$server_name\"}",
     "legendFormat": "Memory-Basic_Avaliable"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{job=\"$server_name\",mountpoint=\"/\",fstype=~\"ext4|xfs\"} * 100) / node_filesystem_size_bytes {job=\"$server_name\",mountpoint=\"/\",fstype=~\"ext4|xfs\"})",
     "legendFormat": "Disk-Usage：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"$server_name\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"$server_name\",device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{device}}_transmit"
    }
   ]
  }
 ]
}