version: '3.7'

services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:5432:5432
    restart: always
     # set shared memory limit
    shm_size: 128mb
    networks:
      - main-network
volumes:
  postgres-data:
    name: postgres-data
networks:
  main-network:
    external: true