version: '3.7'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 127.0.0.1:9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - --storage.tsdb.retention.time=30d
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - main-network
    restart: always
volumes:
  prometheus-data:
    name: prometheus-data
networks:
  main-network:
    external: true
