global:
  scrape_interval: 15s
  scrape_timeout: 5s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: server
    metrics_path: /metrics
    static_configs:
      - targets:
          - '10.0.1.2:9100'
