---
- name: Install Docker and Docker Compose
  hosts: servers
  become: true
  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add GPG Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Start Docker Service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Install Docker Compose
      ansible.builtin.apt:
        name: docker-compose
        state: latest
        update_cache: yes

  handlers:
    - name: Restart Docker
      ansible.builtin.service:
        name: docker
        state: restarted
