name: Build, Push Docker Image, and Deploy

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: ${{ vars.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Add SHORT_SHA env property with commit short sha
      run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.SHORT_SHA }}, ${{ env.DOCKER_IMAGE }}:latest
        push: true
        platforms: linux/amd64

    - name: Log out from Docker Hub
      run: docker logout

    - name: Set up SSH for Ansible
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      env:
        SHORT_SHA: ${{ env.SHORT_SHA }}
      run: |
        cd infra/ansible/
        ansible-playbook -i 00-inventory.yaml 06-deploy-petclinic.yaml
